-- Dragon Dining stock take. Run this once in the Supabase SQL editor.
-- The browser is not granted access. The Vercel server connects as the database owner.

create table if not exists settings (
  key text primary key,
  value text not null
);

create table if not exists rooms (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order integer not null,
  active integer not null default 1
);
create unique index if not exists rooms_name_lower on rooms (lower(name));

create table if not exists products (
  id bigint generated by default as identity primary key,
  external_id text,
  import_fingerprint text,
  room_id bigint not null references rooms(id),
  source text,
  name text not null,
  stock_unit text,
  pack_qty double precision,
  pack_qty_note text,
  item_size text,
  uom text,
  unit_cost_yen integer,
  unit_price_yen integer,
  note text,
  active integer not null default 1,
  created_at text not null,
  updated_at text not null
);
create unique index if not exists products_external_id on products (external_id) where external_id is not null;
create unique index if not exists products_fingerprint on products (import_fingerprint) where import_fingerprint is not null;
create index if not exists products_room on products (room_id);

create table if not exists barcodes (
  code text primary key,
  product_id bigint not null references products(id) on delete cascade
);
create index if not exists barcodes_product on barcodes (product_id);

create table if not exists counts (
  product_id bigint primary key references products(id) on delete cascade,
  counted_room_id bigint references rooms(id),
  qty double precision not null,
  is_exception integer not null default 0,
  updated_at text not null,
  device_id text
);

create table if not exists archives (
  id text primary key,
  label text not null,
  closed_at text not null,
  total_value integer not null,
  counted_n integer not null,
  product_n integer not null,
  snapshot_json text not null
);

create table if not exists import_reports (
  id bigint generated by default as identity primary key,
  created_at text not null,
  mode text not null,
  filename text,
  report_json text not null
);

alter table settings enable row level security;
alter table rooms enable row level security;
alter table products enable row level security;
alter table barcodes enable row level security;
alter table counts enable row level security;
alter table archives enable row level security;
alter table import_reports enable row level security;
