import { isPg, many, one, run } from './query.js'
import { HttpError } from './errors.js'

const TABLES = {
  supplier: { table: 'suppliers', column: 'source' },
  unit: { table: 'units', column: 'stock_unit' },
  measure: { table: 'measures', column: 'uom' },
}

export async function ensureVocab(db) {
  if (isPg(db)) {
    for (const name of ['suppliers', 'units', 'measures']) {
      await run(db, `
        CREATE TABLE IF NOT EXISTS ${name} (
          id bigint generated by default as identity primary key,
          name text not null,
          active integer not null default 1
        )
      `)
      await run(db, `CREATE UNIQUE INDEX IF NOT EXISTS ${name}_name_lower ON ${name} (lower(name))`)
    }
  }
  for (const kind of Object.keys(TABLES)) await rememberUsedNames(db, kind)
}

async function rememberUsedNames(db, kind) {
  const { table, column } = TABLES[kind]
  const rows = await many(db, `
    SELECT DISTINCT ${column} AS name FROM products
    WHERE ${column} IS NOT NULL AND trim(${column}) <> ''
  `)
  for (const row of rows) await addName(db, kind, row.name, { quiet: true })
}

async function addName(db, kind, raw, options = {}) {
  const { table } = TABLES[kind]
  const name = String(raw ?? '').trim().replace(/\s+/g, ' ')
  if (!name) {
    if (options.quiet) return null
    throw new HttpError(400, 'A name is required.')
  }
  const existing = await one(db, `SELECT id, name, active FROM ${table} WHERE lower(name) = lower(?)`, [name])
  if (existing) return existing
  const info = await run(db, `INSERT INTO ${table} (name, active) VALUES (?, 1) RETURNING id`, [name])
  return { id: info.id, name, active: 1 }
}

export async function listVocab(db) {
  const load = async (table) => (await many(db, `SELECT id, name, active FROM ${table} ORDER BY lower(name)`))
    .map((row) => ({ ...row, active: row.active === true || row.active === 1 }))
  return {
    suppliers: await load('suppliers'),
    units: await load('units'),
    measures: await load('measures'),
  }
}

export async function createVocab(db, kind, name) {
  if (!TABLES[kind]) throw new HttpError(400, 'Unknown list.')
  return addName(db, kind, name)
}

export async function updateVocab(db, kind, id, input) {
  const spec = TABLES[kind]
  if (!spec) throw new HttpError(400, 'Unknown list.')
  const current = await one(db, `SELECT id, name, active FROM ${spec.table} WHERE id = ?`, [id])
  if (!current) throw new HttpError(404, 'That entry is not on the list.')
  let name = current.name
  if (input.name != null) {
    name = String(input.name).trim().replace(/\s+/g, ' ')
    if (!name) throw new HttpError(400, 'A name is required.')
    const other = await one(db, `SELECT id FROM ${spec.table} WHERE lower(name) = lower(?) AND id <> ?`, [name, id])
    if (other) throw new HttpError(409, 'That name is already on the list.')
    await run(db, `UPDATE products SET ${spec.column} = ? WHERE lower(${spec.column}) = lower(?)`, [name, current.name])
  }
  let active = current.active
  if (input.active != null) {
    active = input.active ? 1 : 0
    if (!active) {
      const used = await one(db, `SELECT COUNT(*) AS n FROM products WHERE lower(${spec.column}) = lower(?)`, [name])
      if (Number(used.n) > 0) throw new HttpError(400, 'Items still use this. Rename it, or change those items first.')
    }
  }
  await run(db, `UPDATE ${spec.table} SET name = ?, active = ? WHERE id = ?`, [name, active, id])
  return { id, name, active: Boolean(active) }
}
